name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Lavel when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: 1
          GITHU{B_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
